Fix failing files
cse110-sp24-group23/dev-journal pull request #125
Opened 2024-06-04 16:40 UTC by ravishende

Fixes almost all failing files in the linter. simpleMDE will still fail on the simpleMDE being undefined. However, once Sravya switches it to be downloaded in the repo and required in the JS rather than a script linking to the online version, it should go away.

2024-06-04 20:58 UTC, danwyl requested changes
We should find a way for the linter to be happy

2024-06-04 20:58 UTC, danwyl commented on src/dailyLog/simpleMDE.js
Why is it still unhappy with SimpleMDE?

2024-06-04 22:26 UTC, ravishende commented on src/dailyLog/simpleMDE.js
Will do this after 6:20 today. There are issues with functionality after putting simpleMDE in our repo, but until then I don't think we can import simpleMDE by name in the js file, which makes it undefined in the linter's view.

2024-06-05 01:50 UTC, ravishende commented
We decided that pulling simpleMDE into the repo is too much work for very little benefit considering how much time we have left (Iron triangle). Thus, we are just adding SimpleMDE as a global variable in a comment to show the linter that it is coming from the html script tag.

2024-06-05 02:33 UTC, danwyl approved these changes

2024-06-05 02:34 UTC, merged